IYFD/IYFD/Backup/IYFD/Controllers/PlayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IYFD.Utility;

namespace IYFD.Controllers
{
    public class PlayController : UserController
    {
        private IYFDData _data = new IYFDData();

        public ActionResult Index(string id)
        {
            int roundId;
            try
            {
                CheckUser(Models.Content.Play);
                ViewBag.Rounds = _data.GetAllRounds();
                if (!_data.IsItTimeToPlay())
                {
                    ViewBag.PageMessages = "<span style='color: red'>Games are playing!</span>";
                    return View();
                }

                if (!int.TryParse(id, out roundId))
                    roundId = _data.GetAllRounds().FirstOrDefault(x => x.Name == 1).ID;                
            }
            catch (Exception ex)
            {
                ErrorLog.WriteError("Play Index", ex.Message);
                roundId = 2;
                ViewBag.PageMessages = GenericErrorMessage;
                ViewBag.Rounds = string.Empty;
            }
            return View(_data.GetMatchupsForUserByRound(roundId, UserID.Value));
        }

        [HttpPost]
        public ActionResult Index(string id, List<string> teams)
        {
            int roundId;
            int choiceId;
            try
            {
                CheckUser(Models.Content.Play);
                if (!_data.IsItTimeToPlay())
                {
                    ViewBag.PageMessages = "<span style='color: red'>Games are playing!</span>";
                    return View();
                }
                List<int> choiceIds = new List<int>();

                if (!int.TryParse(id, out roundId))
                    roundId = _data.GetAllRounds().FirstOrDefault(x => x.Name == 1).ID;
                foreach (string choice in teams)
                {
                    if (int.TryParse(choice, out choiceId))
                        choiceIds.Add(choiceId);
                }
                ViewBag.Rounds = _data.GetAllRounds();
                _data.SetUserChoices(choiceIds, roundId, UserID.Value);

                ViewBag.PageMessages = "<span style='color: green'>Success!</span>";
            }
            catch (Exception ex)
            {
                ErrorLog.WriteError("Play Index", ex.Message);
                roundId = 2;
                ViewBag.PageMessages = GenericErrorMessage;
            }
            return View(_data.GetMatchupsForUserByRound(roundId, UserID.Value));
        }

    }
}

IYFD/IYFD/Backup/IYFD/Views/Play/Index.cshtml
@{
    Layout = "~/Views/Shared/_playLayout.cshtml";
}
@model List<IYFD.Models.MatchUp>
<div class="adminMenu">
    @Html.Partial("PlayMenu")
</div>
<div class="main-content">
@using (Html.BeginForm())
{
	var i = 1;
	
    <h2>Match Ups</h2>   
    if(!string.IsNullOrEmpty(ViewBag.PageMessages))
    {
		<div>
			@Html.Raw(ViewBag.PageMessages)
		</div>
	} 
	if(Model != null)
	{
		foreach (var region in Model.GroupBy(x => x.Tourny1.Region.ID))
		{
			<div class="regions">
				<h3>@Html.Raw(region.ElementAt(0).Tourny1.Region.Name)</h3>
				<table class="picks">
					<tr>
						<th>Team 1</th>
						<th>Team 2</th>
						<th>Winner</th>
					</tr>
					@foreach (var matchUp in region.OrderBy(y => y.Tourny1.Rank))
					{
						var checked1 = matchUp.UserChoiceId == matchUp.Tourny1.Id;
						var checked2 = matchUp.UserChoiceId == matchUp.Tourny2.Id;
						<tr>
							@if(checked1)
							{
								<td>
									<input id="@Html.Raw(i.ToString())" checked="checked" name="teams" type="checkbox" value="@Html.Raw(matchUp.Tourny1.Id.ToString())" onclick="cW(this.id)" /> @Html.Raw(matchUp.Tourny1.Rank.ToString()). @Html.Raw(matchUp.Tourny1.Team.Name)
								</td>
							}
							else
							{
								<td>
									<input id="@Html.Raw(i.ToString())" name="teams" type="checkbox" value="@Html.Raw(matchUp.Tourny1.Id.ToString())" onclick="cW(this.id)" />@Html.Raw(matchUp.Tourny1.Rank.ToString()). @Html.Raw(matchUp.Tourny1.Team.Name)
								</td>
							}
							
							@{ i++; }
							
							@if(checked2)
							{
								<td>
									<input id="@Html.Raw(i.ToString())" checked="checked" name="teams" type="checkbox" value="@Html.Raw(matchUp.Tourny2.Id.ToString())" onclick="cW(this.id)" />@Html.Raw(matchUp.Tourny2.Rank.ToString()). @Html.Raw(matchUp.Tourny2.Team.Name)
								</td>
							}
							else
							{
								<td>
									<input id="@Html.Raw(i.ToString())" name="teams" type="checkbox" value="@Html.Raw(matchUp.Tourny2.Id.ToString())" onclick="cW(this.id)" />@Html.Raw(matchUp.Tourny2.Rank.ToString()). @Html.Raw(matchUp.Tourny2.Team.Name)
								</td>
							}
							@if(matchUp.Winner.Rank > 0)
							{
								<td>
									@Html.Raw(matchUp.Winner.Rank.ToString()). @Html.Raw(matchUp.Winner.Team.Name)
								</td>
								<script type="text/javascript">
									var id1 = @Html.Raw(i.ToString());
									var id2 = @Html.Raw(i.ToString()) - 1;
									$('#'+id1).attr('disabled', true);
									$('#'+id2).attr('disabled', true);
								</script>
							}
							else
							{
								<td></td>
							}
						</tr>
						i++;
					}
				</table>
			</div>
		}
		<input type="submit" value="Submit Picks" />   
	}
}
</div>
<script type="text/javascript">
    function cW(i) { 
		var e = '#' + i; 
		if(i % 2 == 1) {
			i++;
		}			
		else {
			i--;
		}		
		var oe = '#' + i; 
		$(e).attr('checked', true);
		$(oe).attr('checked', false);
	}
</script>

IYFD/IYFD/Backup/IYFD/Views/Play/PlayMenu.cshtml
@{
    var roundName = 1;
}
<div>
    <ul>
        @foreach(var round in ViewBag.Rounds)
        {
            roundName = round.Name;
            <li>@Html.ActionLink("Round " + roundName, "Index", "Play", new { round.ID }, null)</li>
        }
    </ul>
</div>