IYFD/IYFD/Backup/IYFD/Controllers/EditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IYFD.Models;
using IYFD.Utility;

namespace IYFD.Controllers
{
    public class EditController : UserController
    {
        private Utility.IYFDData _data = new IYFDData();

        public ActionResult Teams(string id)
        {
            int teamId;
            Team team = new Team();

            try
            {
                CheckUser(Models.Content.Teams);
                if (int.TryParse(id, out teamId))
                {
                    team = _data.GetTeamById(teamId);
                }
            }
            catch (Exception ex)
            {
                ErrorLog.WriteError("Edit Team", ex.Message);
            }
            return View(team);
        }

        [HttpPost]
        public ActionResult Teams(string id, string name)
        {
            try
            {
                CheckUser(Models.Content.Teams);
                int teamId;

                if (int.TryParse(id, out teamId))
                {
                    Team team = new Team
                    {
                        ID = teamId,
                        Name = name
                    };
                    _data.UpsertTeam(team);
                }
            }
            catch (Exception ex)
            {
                ErrorLog.WriteError("Edit Team", ex.Message);
            }
            return RedirectToAction("Teams", "Admin");
        }
    }
}

IYFD/IYFD/Backup/IYFD/Views/Admin/AdminMenu.cshtml
<div>
    <ul>
        <li>@Html.ActionLink("Create Tourny Entry", "TournyEntry", "Admin")</li>
        <li>@Html.ActionLink("Match Ups", "MatchUps", "Admin", new { id = "2" }, null)</li>
        <li>@Html.ActionLink("Teams", "Teams", "Admin")</li>
        <li>@Html.ActionLink("Regions", "Regions", "Admin")</li>
        <li>@Html.ActionLink("Generate Tourny", "GenerateTourny", "Admin")</li>
        <li>@Html.ActionLink("Generate Next Matchups", "GenerateMatchups", "Admin")</li>
        <li>@Html.ActionLink("User panel", "UserPanel", "Admin")</li>
        <li>@Html.ActionLink("Game Times", "GamePlayTimes", "Admin")</li>
    </ul>
</div>

IYFD/IYFD/Backup/IYFD/Views/Admin/ChangeUserPass.cshtml
@{
    ViewBag.Title = "ChangeUserPass";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
	<div class="adminMenu">
		@Html.Partial("AdminMenu")
	</div>
    <h2>ChangeUserPass</h2>
    <div>
        <label>Password: </label>
        <input type="text" name="password" />
    </div>
    <input type="submit" value="Overried" />
    
    if(!string.IsNullOrEmpty(ViewBag.PageMessages))
    {
		<div>
			@Html.Raw(ViewBag.PageMessages);
		</div>
	}    
}

IYFD/IYFD/Backup/IYFD/Views/Admin/GamePlayTimes.cshtml
@{
    ViewBag.Title = "GamePlayTimes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<Tuple<DateTime,DateTime>>
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/time/jquery.timepicker.css")" />
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/time/bootstrap-datepicker.css")" />	
<div class="adminMenu">
	@Html.Partial("AdminMenu")
</div>
<div class="main-content-admin">
	<h2>GamePlayTimes</h2>
	<div>
		<table class="regions">
			<tr>
				<th>Start</th>
				<th>End</th>
			</tr>
			@if(Model != null)
			{
				foreach(var times in Model)
				{
					<tr>
						<td>@Html.Raw(times.Item1.ToString())</td>
						<td>@Html.Raw(times.Item2.ToString())</td>
					</tr>
				}
			}
		</table>
	</div>
	@using (Html.BeginForm())
	{
		<div id="datepair" style="clear: left;padding-top: 15px;">
			<h3>Add Times</h3>
			<input name="startDate" type="text" class="date start" />
			<input name="startTime" type="text" class="time start" /> to
			<input name="endDate" type="text" class="date end" />
			<input name="endTime" type="text" class="time end" />
			<input type="submit" value="Enter Times" />
		</div>
	}
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/time/jquery.timepicker.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/time/jquery.datepair.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/time/bootstrap-datepicker.js")"></script>
<script type="text/javascript">
	$(document).ready(function () {
		// initialize input widgets first
		$('#datepair .time').timepicker({
			'showDuration': true,
			'timeFormat': 'g:ia'
		});

		$('#datepair .date').datepicker({
			'format': 'yyyy-m-d',
			'autoclose': true
		});

		// initialize datepair
		$('#datepair').datepair();
	});
</script>

IYFD/IYFD/Backup/IYFD/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="adminMenu">
    @Html.Partial("AdminMenu")
</div>
<div class="main-content-admin">
<h2>Index</h2>
</div>

IYFD/IYFD/Backup/IYFD/Views/Admin/MatchUpMenu.cshtml
@{
    var regionName = 1;
}
<div>
    <ul>
        @foreach(var round in ViewBag.Rounds)
        {
            regionName = round.Name;
            <li>@Html.ActionLink("Round " + regionName, "MatchUps", "Admin", new { round.ID }, null)</li>
        }
    </ul>
</div>

IYFD/IYFD/Backup/IYFD/Views/Admin/MatchUps.cshtml
@{
    ViewBag.Title = "MatchUps";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<IYFD.Models.MatchUp>
<div class="adminMenu">
	@Html.Partial("AdminMenu")
</div>
<div class="main-content-admin">
<h2>Match Ups</h2>   
<div class="round-menu">
	@Html.Partial("MatchUpMenu")
</div>
@using (Html.BeginForm())
{
    foreach (var region in Model.GroupBy(x => x.Tourny1.Region.ID))
    { 
		<div class="regions">
        <h3>@Html.Raw(region.ElementAt(0).Tourny1.Region.Name)</h3>
        <table class="picks">
            <tr>
                <th>Team 1</th>
                <th>Team 2</th>
                <th>Winner</th>
                <th></th>
            </tr>
            @foreach (var matchUp in region.OrderBy(y => y.Tourny1.Rank))
            {
                <tr>
                    <td>@Html.Raw(matchUp.Tourny1.Rank.ToString()). @Html.Raw(matchUp.Tourny1.Team.Name)</td>
                    <td>@Html.Raw(matchUp.Tourny2.Rank.ToString()). @Html.Raw(matchUp.Tourny2.Team.Name)</td>
                    @if(matchUp.Winner.Rank > 0)
                    {
                        <td>@Html.Raw(matchUp.Winner.Rank.ToString()). @Html.Raw(matchUp.Winner.Team.Name)</td>
                    }
                    else{
                        <td></td>
                    }
                    <td>@Html.ActionLink("Pick Winner", "PickWinner", "Admin", new { matchUp.ID }, null)</td>
                </tr>
            }
        </table>
		</div>
    }
}
</div>

IYFD/IYFD/Backup/IYFD/Views/Admin/MimicPlay.cshtml
@{
    ViewBag.Title = "MimicPlay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MimicPlay</h2>
@model List<IYFD.Models.MatchUp>
<div class="adminMenu">
    @Html.Partial("AdminMenu")
</div>
<div class="adminMenu">
    @Html.Partial("MimicPlayMenu")
</div>
@using (Html.BeginForm())
{
	var i = 1;
	
    <h2>Match Ups</h2>  
    
    if(!string.IsNullOrEmpty(ViewBag.PageMessages))
    {
		<div>
			@Html.Raw(ViewBag.PageMessages);
		</div>
	}     
    foreach (var region in Model.GroupBy(x => x.Tourny1.Region.ID))
    { 
        <h3>@Html.Raw(region.ElementAt(0).Tourny1.Region.Name)</h3>
        <table>
            <tr>
                <th>Team 1</th>
                <th>Team 2</th>
                <th>Winner</th>
            </tr>
            @foreach (var matchUp in region.OrderBy(y => y.Tourny1.Rank))
            {
                var checked1 = matchUp.UserChoiceId == matchUp.Tourny1.Id;
                var checked2 = matchUp.UserChoiceId == matchUp.Tourny2.Id;
                <tr>
					@if(checked1)
					{
						<td>
							<input id="@Html.Raw(i.ToString())" checked="checked" name="teams" type="checkbox" value="@Html.Raw(matchUp.Tourny1.Id.ToString())" onclick="cW(this.id)" /> @Html.Raw(matchUp.Tourny1.Rank.ToString()). @Html.Raw(matchUp.Tourny1.Team.Name)
						</td>
					}
					else
					{
						<td>
							<input id="@Html.Raw(i.ToString())" name="teams" type="checkbox" value="@Html.Raw(matchUp.Tourny1.Id.ToString())" onclick="cW(this.id)" />@Html.Raw(matchUp.Tourny1.Rank.ToString()). @Html.Raw(matchUp.Tourny1.Team.Name)
						</td>
					}
					
					@{ i++; }
					
					@if(checked2)
					{
						<td>
							<input id="@Html.Raw(i.ToString())" checked="checked" name="teams" type="checkbox" value="@Html.Raw(matchUp.Tourny2.Id.ToString())" onclick="cW(this.id)" />@Html.Raw(matchUp.Tourny2.Rank.ToString()). @Html.Raw(matchUp.Tourny2.Team.Name)
						</td>
					}
					else
					{
						<td>
							<input id="@Html.Raw(i.ToString())" name="teams" type="checkbox" value="@Html.Raw(matchUp.Tourny2.Id.ToString())" onclick="cW(this.id)" />@Html.Raw(matchUp.Tourny2.Rank.ToString()). @Html.Raw(matchUp.Tourny2.Team.Name)
						</td>
					}
					@if(matchUp.Winner.Rank > 0)
					{
						<td>
							@Html.Raw(matchUp.Winner.Rank.ToString()). @Html.Raw(matchUp.Winner.Team.Name)
						</td>
					}
					else
					{
						<td></td>
					}
                </tr>
                i++;
            }
        </table>
    }
    <input type="submit" value="Submit Picks" />
}
<script type="text/javascript">
    function cW(i) { 
		var e = '#' + i; 
		if(i % 2 == 1) {
			i++;
		}			
		else {
			i--;
		}		
		var oe = '#' + i; 
		$(e).attr('checked', true);
		$(oe).attr('checked', false);
	}
</script>

IYFD/IYFD/Backup/IYFD/Views/Admin/MimicPlayMenu.cshtml
@{
    var roundName = 1;
}
<div>
    <ul>
        @foreach(var round in ViewBag.Rounds)
        {
            roundName = round.Name;
            <li>@Html.ActionLink("Round " + roundName, "MimicPlay", "Admin", new { id = ViewBag.MimicUserID, round = round.ID }, null)</li>
        }
    </ul>
</div>

IYFD/IYFD/Backup/IYFD/Views/Admin/PickWinner.cshtml
@{
    ViewBag.Title = "Pick Matchup Winner";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    <div id="adminMenu">
        @Html.Partial("AdminMenu")
    </div>
    <div id="adminMenu">
        @Html.Partial("MatchUpMenu")
    </div>
    <h2>Pick Matchup Winner</h2>
    <table>
        <tr>
            <th>Team 1</th>
            <th>Team 2</th>
            <th>Winner</th>
        </tr>
        <tr>
            <td>@Html.Raw(Model.Tourny1.Team.Name)</td>
            <td>@Html.Raw(Model.Tourny2.Team.Name)</td>
            <td>
                <select name="winner">
                    <option value="@Html.Raw(Model.Tourny1.Id.ToString())">@Html.Raw(Model.Tourny1.Team.Name)</option>
                    <option value="@Html.Raw(Model.Tourny2.Id.ToString())">@Html.Raw(Model.Tourny2.Team.Name)</option>
                </select>
            </td>
        </tr>
    </table>
    <input type="submit" value="Pick Winner" />
    
    if(!string.IsNullOrEmpty(ViewBag.PageMessages))
    {
		<div>
			@Html.Raw(ViewBag.PageMessages);
		</div>
	}    
}

IYFD/IYFD/Backup/IYFD/Views/Admin/Regions.cshtml
@model IYFD.Models.Region

@{
    ViewBag.Title = "Regions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<div class="adminMenu">
    @Html.Partial("AdminMenu")
</div>
<div class="main-content-admin">
@using (Html.BeginForm()) {
    <h2>Regions</h2>
    <div>
        <fieldset>
            <legend>Current Regions</legend>
            <ul>
            @foreach (var region in ViewBag.Regions)
            {
                <li>@Html.Raw(region.Name)</li>
            }
            </ul>
        </fieldset>
        @if(ViewBag.Regions.Count < 4)
        {
        <fieldset>
            <legend>Region Information</legend>
            <div class="editor-label">
                @Html.LabelFor(m => m.Name)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Name)
                @Html.ValidationMessageFor(m => m.Name)
            </div>
            <p>
                <input type="submit" value="Add Region" />
            </p>
        </fieldset>
        }

        @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
        {            
            <div>
                @Html.Raw(ViewBag.ErrorMessage)
            </div>
        }
    </div>
}
</div>

IYFD/IYFD/Backup/IYFD/Views/Admin/Roles.cshtml
@{
    ViewBag.Title = "Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var roleName = "";
}
<h2>Roles</h2>
<ul>
@foreach(var role in ViewBag.Roles)
{
    roleName = role.Name;
    <li>@Html.ActionLink(roleName.ToString(), "Roles", "Admin", new { role.ID }, null)</li>
}
</ul>
<fieldset>
    <legend>
        Add new role
    </legend>
    @if(string.IsNullOrEmpty(ViewBag.RoundId))
    {
        <div>
            <label>Role: </label>
            <input type="text" name="roleName" />
        </div>
    }
    else
    {
        <input type="hidden" name="roleName" value="" />
    }
    <div>
        <ul>
            @foreach(var keyValuePair in ViewBag.Content)
            {
                <li><input type="checkbox" name="contentIds" value="@Html.Raw(keyValuePair.Key.ToString())" /> @Html.Raw(keyValuePair.Value.ToString())</li>
            }
        </ul>
    </div>
</fieldset>

IYFD/IYFD/Backup/IYFD/Views/Admin/Teams.cshtml
@model IYFD.Models.Team

@{
    ViewBag.Title = "Teams";
    Layout = "~/Views/Shared/_Layout.cshtml";
	var i = 1;
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


<div class="adminMenu">
    @Html.Partial("AdminMenu")
</div>
<div class="main-content-admin">
@using (Html.BeginForm()) {

    <h2>Teams</h2>
    <div>
        <fieldset>
            <legend>Current Teams</legend>
            <table class='regions'>
				<tr>
					<th>Team</th>
					<th>Edit</th>
				</tr>
				@foreach (var team in ViewBag.Teams)
				{
					<tr>
						<td>@Html.Raw(team.Name)</td>
						<td><a href="@Url.Action("Teams", "Edit")/@team.ID">Edit</a></td>
					</tr>
				
					if(i >= 16)
					{
						i = 0;
						@Html.Raw("</table><table class='regions'><tr><th>Team</th><th>Edit</th></tr>");
					}
					i++;
				}
			</table>
        </fieldset>
        <fieldset>
            <legend>Team Information</legend>
            <div class="editor-label">
                @Html.LabelFor(m => m.Name)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Name)
                @Html.ValidationMessageFor(m => m.Name)
            </div>
            <p>
                <input type="submit" value="Add Team" />
            </p>
        </fieldset>
        @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
        {            
            <div>
                @Html.Raw(ViewBag.ErrorMessage)
            </div>
        }
    </div>
}
</div>

IYFD/IYFD/Backup/IYFD/Views/Admin/TournyEntry.cshtml
@model IYFD.Models.Tourny
@{
    ViewBag.Title = "TournyEntry";
    Layout = "~/Views/Shared/_Layout.cshtml";
	var i = 1;
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<div class="adminMenu">
    @Html.Partial("AdminMenu")
</div>
<div class="main-content-admin">
@using (Html.BeginForm())
{
<h2>Tournament Entries</h2>
if(!string.IsNullOrEmpty(ViewBag.PageMessages))
{
	<div>
		@Html.Raw(ViewBag.PageMessages)
	</div>
} 
<div>
	<span id="tce">Hide</span><span> current entries</span>
    <fieldset id="ce">
        <legend>Current Entries</legend>
        <table class="regions">
            <tr>
                <th>Rank</th>
                <th>Region</th>
                <th>Team</th>
            </tr>
            @foreach (var tourny in ViewBag.Tournies)
            {
                <tr>
                    <td>@tourny.Rank</td>
                    <td>@tourny.Region.Name</td>
                    <td>@tourny.Team.Name</td>
                </tr>
				
				if(i >= 16)
				{
					i = 0;
					@Html.Raw("</table><table class='regions'><tr><th>Rank</th><th>Region</th><th>Team</th></tr>");
				}
				i++;
            }
        </table>
    </fieldset>
</div>
<div>
    @if(ViewBag.Tournies.Count < 64)
    {
    <fieldset>
        <legend>Create Tourny</legend>
        <fieldset>
            <legend>Team</legend>            
            <select name="teams">
                @foreach (var team in ViewBag.Teams)
                {
                    <option value="@team.ID">@Html.Raw(team.Name)</option>
                }
            </select>
        </fieldset>
        <fieldset>
            <legend>Region</legend>
            <select name="regions">
                @foreach (var region in ViewBag.Regions)
                {
                    <option value="@region.ID">@Html.Raw(region.Name)</option>
                }
            </select>
        </fieldset>
        <fieldset>
            <legend>Rank</legend>
            <select name="ranks">
                @foreach (var rank in ViewBag.Ranks)
                {
                    <option value="@rank.ID">@Html.Raw(rank.Name.ToString())</option>
                }
            </select>
        </fieldset>
        <input type="submit" value="Create Entry" />
    </fieldset>
    }
    
    @if(!string.IsNullOrEmpty(ViewBag.PageMessages))
    {
		<div>
			@Html.Raw(ViewBag.PageMessages);
		</div>
	}    
</div>
}
</div>
<script type="text/javascript">
	$('#tce').click(function(){
		var a = $('#tce').text();
		if(a=='Show'){
			$('#ce').show();
			$('#tce').text('Hide');
		}
		else{
			$('#ce').hide();
			$('#tce').text('Show');
		}
	});
</script>

IYFD/IYFD/Backup/IYFD/Views/Admin/UserPanel.cshtml
@{
    ViewBag.Title = "UserPanel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="adminMenu">
    @Html.Partial("AdminMenu")
</div>
<div class="main-content-admin">
<h2>UserPanel</h2>
<table>
    <tr>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Mimic Play</th>
        <th>Activate</th>
        <th>Change Password</th>
    </tr>
    @foreach(var user in Model)
    {
        <tr>
            <td>@Html.Raw(user.Username)</td>
            <td>@Html.Raw(user.FirstName)</td>
            <td>@Html.Raw(user.LastName)</td>
            <td>@Html.ActionLink("Mimic Play", "MimicPlay", "Admin", new { id=user.ID, round=ViewBag.Round }, null)</td>
            @if(!user.Active)
            {
                <td>@Html.ActionLink("Activate", "Activate", "Admin", new { user.ID }, null)</td>
            }
            else
            {
                <td>Active</td>
            }
            <td>@Html.ActionLink("Change Password", "ChangeUserPass", "Admin", new { user.ID }, null)</td>
        </tr>
    }
</table>
</div>